CREATE OR REPLACE VIEW VW_GARAJLAR AS SELECT ID,KULLANICI_ADI , MI_STYLE, GARAJ_ADI,ILCEADI AS ILCE_ADI, 
ILCE_ID, GARAJ_KODU,
MDSYS.SDO_CS.TRANSFORM(vg.GEOLOC , 7932, 4326) AS GEOLOC,KAPASITESI, MEVCUT_ARAC ,
ISLETME_BOLGESI ,ISLETME_ALT_BOLGESI , DURUMU 
FROM V_GARAJ vg 


/* v_garaj tablosu yerine base katmanlardaki garaj tablosu kullanılabilir.
