CREATE OR REPLACE VIEW SDE.VW_DURAKERISIMLISTESI AS
SELECT d.ESKI_DURAK_ID AS ESKI_DURAK_ID, d.ADI AS DURAK_ADI,
 CAST(ROW_NUMBER() OVER (ORDER BY d.OBJECTID) AS NUMBER(38, 0)) AS ROW_ID,
d.DURAK_KODU AS DURAK_KODU, d.OBJECTID,
ii.ILCEADI AS ILCE_ADI, m.ADI AS MAHALLE_ADI, dd.K, d.ENGELLI_RAMPA,
dd.O1, dd.O2, dd.O3, dd.O4,
d.YON_BILGISI, d.KALDIRIM_GENISLIGI, dd.Z,  d.SHAPE, SDE.ST_X(d.SHAPE) AS X, SDE.ST_Y(d.SHAPE) AS Y
FROM SDE.DURAK d
INNER JOIN SDE.DURAK_DETAY dd ON d.ESKI_DURAK_ID = dd.DURAK_ID
LEFT JOIN SDE.ILLER i ON i.TUIK_IL_KODU = d.ILID
LEFT JOIN SDE.ILCELER ii ON ii.TUIK_ILCE_KODU = d.ILCEID
LEFT JOIN SDE.MAHALLELER m ON m.TUIK_MAHALLE_KODU = d.MAHALLEID;


/*durak detay tablosu base katman olacak. durakların kaldırım vb. gibi kısımlara olan mesafeleri yer almaktadır.
BASE TABLOLARDAN ÇÖZÜMLENİYOR.