CREATE OR REPLACE VIEW VW_GUZERGAHSIZDURAKLAR AS SELECT D.ID,D.ADI,D.DURAK_KODU, MDSYS.SDO_CS.TRANSFORM(D.GEOLOC , 7932, 4326) AS GEOLOC
FROM DURAK D WHERE  D.DURAK_KODU>0 AND D.ID NOT IN(SELECT DISTINCT  S.BA_DURAK_ID FROM GUZERGAH_SEGMENT GS 
JOIN SEGMENT S ON GS.SEGMENT_ID=S.ID
WHERE S.TIP!=1 AND S.BA_DURAK_ID IS NOT NULL 
UNION ALL
SELECT DISTINCT  S.BI_DURAK_ID FROM GUZERGAH_SEGMENT GS 
JOIN SEGMENT S ON GS.SEGMENT_ID=S.ID
WHERE S.TIP!=3 AND S.BI_DURAK_ID IS NOT NULL) ORDER BY ID 


/*???? TIPI PASIFE CEKILEN DURAKLAR
