CREATE OR REPLACE VIEW VW_DURAKSUREMESAFE AS
SELECT (SELECT d.SHAPE FROM DURAK d WHERE d.ESKI_DURAK_ID = V_DURAK_SIRA.BI_DURAK_ID)    AS SHAPE_BI,
       (SELECT d2.SHAPE FROM DURAK d2 WHERE d2.ESKI_DURAK_ID = V_DURAK_SIRA.BA_DURAK_ID) AS SHAPE_BA,
       ROUND((V_DURAK_SIRA.MESAFE) / 1000, 2)                                            AS MESAFE,
       V_DURAK_SIRA.BASLANGIC_ADI,
       V_DURAK_SIRA.BITIS_ADI,
       V_DURAK_SIRA.HAT_KODU,
       V_DURAK_SIRA.SIRA,
       V_DURAK_SIRA.SEGMENT_ID,
       V_DURAK_SIRA.GUZERGAH_KODU,
       ROUND((V_DURAK_SIRA.SURE) / 60, 2)                                                AS SURE,
       V_DURAK_SIRA.BA_DURAK_ID,
       V_DURAK_SIRA.BI_DURAK_ID,
       CAST(ROW_NUMBER() OVER (ORDER BY V_DURAK_SIRA.OBJECTID) AS NUMBER(38, 0))         AS ROW_ID
FROM SDE.V_DURAK_SIRA
WHERE BI_DURAK_ID IS NOT NULL


-- TABLE: DURAKSUREMESAFE
-- BASDURKOD INT, BITDURKOD INT, MESAFE FLOAT, SURE DATETIME
