SELECT DURAK_KODU, ADI AS DURAK_ADI, geom.X AS ENLEM, geom.Y AS BOYLAM FROM DURAK d 
JOIN SEGMENT s ON s.BA_DURAK_ID = d.ID
JOIN GUZERGAH_SEGMENT gs ON gs.SEGMENT_ID = s.ID 
JOIN GUZERGAH g ON g.ID = gs.GUZERGAH_ID 
JOIN HAT h ON h.ID = g.HAT_ID , TABLE(MDSYS.SDO_UTIL.GETVERTICES(d.GEOLOC)) geom



/* hatbasıhatsonu