CREATE OR REPLACE VIEW VW_DURAKLAR AS 
SELECT ID,ADI,DURAK_KODU, DURUMU,DURAK_TIPI,YON_BILGISI, AKILLI_DURAK_DURUMU, KONMA_TARIHI,SOKULME_TARIHI 
ENERJI_DURUMU, MODUL_ADEDI, ISLETME_BOLGESI, ISLETME_ALT_BOLGESI, KALDIRIM_GENISLIGI, FIZIKI_DURUMU,
ADRES,SON_GUNCELLEME_TARIHI,YAPILIS_TARIHI,ACIKLAMA, ENGELLI_RAMPA,ENGELLI_KULLANIM,
KALDIRILDI_MI,MODUL_DURAK_ID, DURAKLAMA_DURUMU, IL_ADI,ILCE_ADI, MAHALLE_ADI,ABONELIK_DURUMU,
ELEKTIRIK_DURUMU ,AKTIF_DURUMU,KULLANICI_ADI,MDSYS.SDO_CS.TRANSFORM(vd.GEOLOC , 7932, 4326) AS GEOLOC,
CEP_VAR,DURAK_KISA_ADI,SOFOR_DEGISIM_NOKTASI,SOFOR_DEGISIM_NOKTASI_ADI,IKMAL_NOKTASI_TIPI,
IKMAL_NOKTASI_ADI,PERON_KODU,LEVHA_VAR,ILID,ILCEID,PERON_DURAGI,MAHALLEID,FIZIKI_DURUM,PERON_ADI,
MODUL_DURAK_DURUMU,DURAK_TIPI_ID FROM V_DURAK vd ORDER BY DURAK_KODU 



/*burada v_durak yerine normal base durak tablosu kullanılabilir.
