--GYY .NET Reports 

/* 
 Report 2: 
 Duraklar Cephe Olculeri Raporu:
 ** View Name: VW_DURAKCEPHEOLCULERI
 

*/  

CREATE OR REPLACE VIEW VW_DURAKCEPHEOLCULERI AS SELECT d.ID AS DURAK_ID, d.ADI AS DURAK_ADI,
d.DURAK_KODU AS DURAK_KODU, CAST(ROW_NUMBER() OVER (ORDER BY d.ID) AS NUMBER(38, 0)) AS OBJECTID,
dd.O1, dd.O2, dd.O3, dd.O4, 
MDSYS.SDO_CS.TRANSFORM(d.GEOLOC, 7932, 4326) AS GEOLOC 
FROM DURAK d 
INNER JOIN DURAK_DETAY dd ON d.ID = dd.DURAK_ID 

SELECT * FROM VW_DURAKCEPHEOLCULERIRAPORU vd 

-- sde
CREATE OR REPLACE VIEW VW_DURAKCEPHEOLCULERI AS SELECT d.ESKI_DURAK_ID AS DURAK_ID, d.ADI AS DURAK_ADI,
d.DURAK_KODU AS DURAK_KODU, CAST(ROW_NUMBER() OVER (ORDER BY d.ESKI_DURAK_ID) AS NUMBER(38, 0)) AS ROW_ID,
dd.O1, dd.O2, dd.O3, dd.O4, 
d.SHAPE 
FROM SDE.DURAK d 
INNER JOIN SDE.DURAK_DETAY dd ON d.ESKI_DURAK_ID = dd.DURAK_ID 