-- test
SELECT * FROM sde.DURAK d;
SELECT * FROM SDE.TEST_DURAK;
SELECT * FROM SDE.TEST_DURAK_EVW tde;

-- YENI DURAKLAR: Created since X date
-- CREATED_DURAK_VW
-- View olusturmadim cunku EVW yayinlanacak oradan filtrelenir
SELECT * FROM SDE.DURAK_EVW td WHERE CREATED_DATE  > TO_DATE('2022-04-27 12:46:00', 'YY-MM-DD HH24:MI:SS');

-- IPTAL EDILEN DURAKLAR: Deleted since X date
-- EXAMPLE 
CREATE OR REPLACE VIEW SDE.SILINEN_DURAK_VW AS SELECT * FROM SDE.TEST_DURAK td WHERE 
GDB_TO_DATE > TO_DATE('2022-04-29 08:23:07','YY-MM-DD HH24:MI:SS') 
AND GDB_TO_DATE != TO_DATE('9999-12-31 23:59:59', 'YY-MM-DD HH24:MI:SS');

-- IPTAL EDILEN DURAKLAR: Retrieve deleted all
-- SILINEN_DURAK_EVW
CREATE OR REPLACE VIEW SDE.SILINEN_DURAK_VW AS 
SELECT tde.*, CAST(ROW_NUMBER() OVER (ORDER BY tde.OBJECTID) AS NUMBER(38, 0)) AS ROW_ID
FROM SDE.DURAK tde WHERE tde.GLOBALID NOT IN (SELECT GLOBALID FROM SDE.DURAK_EVW td);


-- OTELEME YAPILAN DURAKLAR: Modified geo only and filter deleted
CREATE OR REPLACE VIEW SDE.OTELENEN_DURAK_VW AS 

SELECT td.*, CAST(ROW_NUMBER() OVER (ORDER BY td.OBJECTID) AS NUMBER(38, 0)) AS ROW_ID FROM SDE.DURAK_EVW td
JOIN SDE.DURAK tde ON td.GLOBALID = tde.GLOBALID 
WHERE sde.st_equals(td.SHAPE, tde.SHAPE) = 1;

-- SOZEL DEGISEN DURAKLAR: Modified except geo
CREATE OR REPLACE VIEW SDE.SOZEL_DEGISEN_DURAK_VW AS 
SELECT td.*, CAST(ROW_NUMBER() OVER (ORDER BY td.OBJECTID) AS NUMBER(38, 0)) AS ROW_ID FROM SDE.DURAK_EVW td
JOIN SDE.DURAK tde ON td.GLOBALID = tde.GLOBALID 
WHERE td.SHAPE = tde.SHAPE AND 
(
td.DURAK_KODU != tde.DURAK_KODU OR
td.YON_BILGISI != tde.YON_BILGISI OR 
td.DURAK_TIPI != tde.DURAK_TIPI OR 
td.KONMA_TARIHI != tde.KONMA_TARIHI OR
td.SOKULME_TARIHI != tde.SOKULME_TARIHI OR
td.AKTIF_DURUMU != tde.AKTIF_DURUMU OR
td.MODUL_ADEDI != tde.MODUL_ADEDI OR
td.KALDIRIM_GENISLIGI != tde.KALDIRIM_GENISLIGI OR
td.ADRES != tde.ADRES OR
td.ACIKLAMA != tde.ACIKLAMA OR
td.DURAKLAMA_DURUMU != tde.DURAKLAMA_DURUMU OR
td.ILID != tde.ILID OR
td.ILCEID != tde.ILCEID OR
td.MAHALLEID != tde.MAHALLEID OR
td.DURAK_KISA_ADI != tde.DURAK_KISA_ADI OR
td.LEVHA_VAR != tde.LEVHA_VAR OR
td.PERON_KODU != tde.PERON_KODU OR
td.MODUL_DURAK_DURUMU != tde.MODUL_DURAK_DURUMU OR
td.DURAK_KUME_ID != tde.DURAK_KUME_ID OR
td.PERON_DURAGI != tde.PERON_DURAGI OR
td.DURUMU != tde.DURUMU OR
td.FIZIKI_DURUM != tde.FIZIKI_DURUM OR
td.KALDIRILDI_MI != tde.KALDIRILDI_MI OR
td.YRDMC_FORM_FIZIKI_DURUM != tde.YRDMC_FORM_FIZIKI_DURUM OR
td.ENGELLI_RAMPA != tde.ENGELLI_RAMPA OR
td.ENGELLI_KULLANIM != tde.ENGELLI_KULLANIM OR
td.AKILLI_DURAK_DURUMU != tde.AKILLI_DURAK_DURUMU OR
td.ABONELIK_DURUMU != tde.ABONELIK_DURUMU OR
td.ENERJI_DURUMU != tde.ENERJI_DURUMU OR
td.ELEKTRIK_DURUMU != tde.ELEKTRIK_DURUMU OR
td.CEP_VAR != tde.CEP_VAR OR
td.SOFOR_DEGISIM_NOKTASI != tde.SOFOR_DEGISIM_NOKTASI OR
td.IKMAL_NOKTASI_TIPI != tde.IKMAL_NOKTASI_TIPI OR
td.ISLETME_BOLGESI != tde.ISLETME_BOLGESI OR
td.ISLETME_ALT_BOLGESI != tde.ISLETME_ALT_BOLGESI OR
td.MODUL_DURAK_ID != tde.MODUL_DURAK_ID
);


