SELECT d.ADI AS DURAK_ADI, 
d.DURAK_KODU AS DURAK_KODU,d.DURAK_TIPI AS DURAK_TIPI, CAST(ROW_NUMBER() OVER (ORDER BY d.ID) AS NUMBER(38, 0)) AS OBJECTID,
dac.ANKET_SORU_ID,dac.CEVAP,ii.ILCEADI AS ILCE_ADI, m.ADI AS MAHALLE_ADI,
MDSYS.SDO_CS.TRANSFORM(d.GEOLOC, 7932, 4326) AS GEOLOC 
FROM DURAK d 
INNER JOIN DURAK_ANKET_CEVAP dac ON d.ID = dac.DURAK_ID
LEFT JOIN ILCELER ii ON ii.TUIK_ILCE_KODU = d.ILCEID
LEFT JOIN MAHALLELER m ON m.TUIK_MAHALLE_KODU = d.MAHALLEID;

