--GYY .NET Reports 

/* 
 Report 3: 
 Duraklarin Guzergahlari Raporu:
 ** View Name: VW_DURAKGUZERGAH
 

*/  

CREATE OR REPLACE VIEW VW_DURAKGUZERGAH AS SELECT D.DURAK_KODU,D.ID,D.ADI, G.GUZERGAH_KODU, 
MDSYS.SDO_CS.TRANSFORM(d.GEOLOC , 7932, 4326) AS GEOLOC,(SELECT COUNT (*) FROM HAT H WHERE H.ID=G.HAT_ID) AS DURAKTAN_GECEN_HATSAYISI FROM GUZERGAH G 
JOIN GUZERGAH_SEGMENT GS ON G.ID = GS.GUZERGAH_ID 
JOIN SEGMENT S ON GS.SEGMENT_ID = S.ID 
JOIN DURAK  D ON D.ID = S.BI_DURAK_ID WHERE S.TIP = 3 
UNION ALL 
SELECT  D.DURAK_KODU,D.ID,D.ADI, G.GUZERGAH_KODU, MDSYS.SDO_CS.TRANSFORM(d.GEOLOC , 7932, 4326) AS GEOLOC,
(SELECT COUNT(*) FROM HAT H WHERE H.ID = G.HAT_ID ) AS DURAKTAN_GECEN_HATSAYISI FROM GUZERGAH G 
JOIN GUZERGAH_SEGMENT GS ON G.ID = GS.GUZERGAH_ID 
JOIN SEGMENT S ON GS.SEGMENT_ID = S.ID  
JOIN DURAK D ON D.ID = S.BA_DURAK_ID WHERE S.TIP = 1

-- sde
SELECT D.DURAK_KODU, D.ESKI_DURAK_ID, D.ADI, G.GUZERGAH_KODU,
D.SHAPE,(SELECT COUNT (*) FROM HAT H WHERE H.ID=G.HAT_ID) AS DURAKTAN_GECEN_HATSAYISI FROM GUZERGAH G 
JOIN SDE.GUZERGAH_SEGMENT GS ON G.ID = GS.GUZERGAH_ID 
JOIN SDE.SEGMENT S ON GS.SEGMENT_ID = S.ID 
JOIN SDE.DURAK D ON D.ESKI_DURAK_ID = S.BI_DURAK_ID WHERE S.TIP = 3 
UNION ALL 
SELECT  D.DURAK_KODU,D.ESKI_DURAK_ID,D.ADI, G.GUZERGAH_KODU, D.SHAPE,
(SELECT COUNT(*) FROM HAT H WHERE H.ID = G.HAT_ID ) AS DURAKTAN_GECEN_HATSAYISI FROM GUZERGAH G 
JOIN GUZERGAH_SEGMENT GS ON G.ID = GS.GUZERGAH_ID 
JOIN SEGMENT S ON GS.SEGMENT_ID = S.ID  
JOIN DURAK D ON D.ESKI_DURAK_ID = S.BA_DURAK_ID WHERE S.TIP = 1;
