
--GYY .NET Reports 

/* 
 Report 13: 
 Guzergah ilk-Son Duraklar :
 ** View Name: VW_GILKSONDURAKLAR
 
 

*/  

CREATE OR REPLACE VIEW VW_GILKSONDURAKLAR AS SELECT MDSYS.SDO_CS.TRANSFORM(gor.GEOLOC , 7932, 4326) AS GEOLOC,
KESIT_KODU, DURAK_KODU AS DURAK_KODU_A ,
ENVARTER_KODU AS DURAK_KODU_B, MESAFE, SURE 
FROM GUZERGAH_OLUKM_REPORT gor WHERE GUZERGAH_KODU LIKE 'O_BOS%';
