SELECT HAT_KODU ,GUZERGAH_KODU,SIRA ,D.DURAK_TIPI , D.ADI  FROM V_DURAK_SIRA vds WHERE BAS_DURAK_MI = 1
JOIN DURAK D ON D.ID= vds.BA_DURAK_ID



SELECT HAT_KODU ,GUZERGAH_KODU,SIRA, BA_DURAK_ID FROM V_DURAK_SIRA vds 

SELECT BA_DURAK_ID FROM V_DURAK_SIRA vds ORDER BY BA_DURAK_ID 


SELECT ID FROM DURAK 
