-- Scratch 
-- BANKAI TRAINING

SELECT d.ID AS DURAK_ID, d.ADI AS "DURAK ADI",	
d.DURAK_KODU, CAST(ROW_NUMBER() OVER (ORDER BY d.ID) AS NUMBER(38, 0)) AS OBJECTID,
ii.ILCEADI, m.ADI AS MAHALLE_ADI, dd.K,
yder.TEXT AS ENGELLI_RAMPA,
dd.O1, dd.O2, dd.O3, dd.O4, 
d.YON_BILGISI, d.KALDIRIM_GENISLIGI, dd.Z,  MDSYS.SDO_CS.TRANSFORM(d.GEOLOC, 7932, 4326) AS GEOLOC
FROM DURAK d
INNER JOIN DURAK_DETAY dd ON d.ID = dd.DURAK_ID
LEFT JOIN YRDMC_DURAK_ENGELLI_RAMPA yder ON yder.VALUE = d.ENGELLI_RAMPA
LEFT JOIN ILLER i ON i.TUIK_IL_KODU = d.ILID
LEFT JOIN ILCELER ii ON ii.TUIK_ILCE_KODU = d.ILCEID
LEFT JOIN MAHALLELER m ON m.TUIK_MAHALLE_KODU = d.MAHALLEID; 