SELECT * FROM USER_SYS_PRIVS; 
SELECT * FROM USER_TAB_PRIVS;
SELECT * FROM USER_ROLE_PRIVS;


GRANT EXECUTE ON DBMS_PIPE TO public;
  GRANT EXECUTE ON DBMS_LOCK TO public;
  GRANT EXECUTE ON DBMS_UTILITY TO public;
  GRANT EXECUTE ON DBMS_SQL TO public;
  GRANT EXECUTE ON DBMS_LOB TO public;
  GRANT EXECUTE ON UTL_RAW TO public;
  GRANT EXECUTE ON DBMS_CRYPTO TO sde;

EXEC dbms_utility.compile_schema('SDE');

SELECT * FROM user_libraries;

INSERT INTO SDE.ST_SPATIAL_REFERENCES (SR_NAME, SRID, 
X_OFFSET, Y_OFFSET, XYUNITS, Z_OFFSET, Z_SCALE, M_OFFSET, 
M_SCALE, MIN_X, MAX_X, MIN_Y, MAX_Y, MIN_Z, MAX_Z, MIN_M, 
MAX_M, CS_ID, CS_NAME, CS_TYPE, ORGANIZATION, 
ORG_COORDSYS_ID, DEFINITION, DESCRIPTION)
VALUES (
 'IETT7932', 
 7932,
 -400,
 -400,
 1000000000, 
 -100000, 
 100000, 
 -100000, 
 100000, 
 9.999E35,
 -9.999E35, 
 9.999E35, 
 -9.999E35, 
 9.999E35, 
 -9.999E35, 
 9.999E35, 
 -9.999E35, 
 7932, 
 'IETT7932',
 'PROJECTED', 
 NULL,
 NULL,
 'GEOGCS["GCS_ITRF_1996",
        DATUM["D_ITRF_1996",
            SPHEROID["GRS_1980",6378137.0,298.257222101]],
        PRIMEM["Greenwich",0.0],
        UNIT["Degree",0.017453292519943295]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["central_meridian",30.0],
    PARAMETER["latitude_of_origin",0.0],
    PARAMETER["scale_factor",1],
    PARAMETER["false_easting",500000.0],
    PARAMETER["false_northing",0.0],
    UNIT["m",1.0]]',
 'IETT7932'
);

SELECT * FROM sde.ST_SPATIAL_REFERENCES ssr WHERE SR_NAME LIKE '%IETT%';


UPDATE sde.ST_SPATIAL_REFERENCES SET SRID = 7932 WHERE SR_NAME = 'IETT7932';


SELECT T.BAS_DURAK_MI,T.HAT_KODU,T.GUZERGAH_KODU,T.BA_DURAK_ID,
T.BASLANGIC_ADI, D.GEOLOC, 
T.SIRA, CAST(ROW_NUMBER () OVER(ORDER BY T.ID) AS NUMBER (38, 0)) AS TOID  
FROM HATYONETIM.V_DURAK_SIRA T   
JOIN DURAK D ON D.ID=T.BA_DURAK_ID WHERE T.BAS_DURAK_MI=1;

SELECT * FROM HATYONETIM.DURAK;

INSERT INTO SDE.DURAK
SELECT * FROM HATYONETIM.DURAK
WHERE 1=1;


SELECT * FROM SDE.TABLE_REGISTRY tr WHERE TABLE_NAME = 'DURAK_UMUT'

SELECT SHAPE FROM SDE.GDB_ITEMS gi WHERE NAME = 'HATYONETIM.DURAK_UMUT';

UPDATE SDE.GDB_ITEMS SET SHAPE.SRID=7932 WHERE NAME = 'HATYONETIM.DURAK_UMUT';

UPDATE SDE.GDB_ITEMS T
SET SHAPE.SDO_SRID = 7932
WHERE T.NAME = 'HATYONETIM.DURAK_UMUT';
